server:
  port: 10010

spring:
  application:
    name: coupon-merchant-admin
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yml
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


knife4j:
  enable: true
  setting:
    language: zh-CN

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: coupon_merchant-admin${unique-name:}-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

xxl-job:
  enabled: false
  access-token: default_token
  admin:
    addresses: http://localhost:8088/xxl-job-admin
  executor:
    application-name: merchant-admin
    ip: 127.0.0.1
    log-retention-days: 30
    port: 19999

