server:
  port: 10020

spring:
  application:
    name: coupon-engine
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: false
      password: nacos
      username: nacos
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  setting:
    language: zh-CN

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: coupon_engine${unique-name:}-service`11`1_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

coupon:
  user-coupon-list:
    save-cache:
      type: direct # 有两个选项：direct 在流程里直接操作，binlog 通过解析数据库日志后操作

engine:
  cache:
    redis:
      bloom-filter:
        cancel-remind:
          name: cancel_remind_cache_penetration_bloom_filter${unique-name:}