server:
  port: 10050

spring:
  application:
    name: coupon-search
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: false
      password: nacos
      username: nacos
  redis:
    host: localhost
    port: 6379
  elasticsearch:
    uris: 127.0.0.1:9200



knife4j:
  enable: true
  setting:
    language: zh-CN



rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: oneCoupon_search${unique-name:}-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1